### ISSUE TITLE
Unable to generate encryption Key

### ISSUE THREAD

**Issue by AnushaVanama** [JoshCMoore/Massmine-for-the-Masses#223]
I tried installing massmine in Ubuntu desktop by following the instructions given in the user manual. I got stuck while generating an encryption key.

1.2.5 Initializing settings
MYVAR=$(python django/webapp/manage.py generate_encryption_key)

Received below error message after running the above command
django.core.exceptions.ImproperlyConfigured: FIELD_ENCRYPTION_KEY must be defined in settings
![encryptionfailed](https://user-images.githubusercontent.com/49127881/64481085-e8135900-d1a2-11e9-9e2e-83d4e2229a97.png)

@JoshCMoore @PatriciaTanzer @LoganHornbuckle @Momac546 - Please find the attached files related to this error and Kindly let me know how to define FIELD_ENCRYPTION_KEY in settings.
[Related files.zip](https://github.com/JoshCMoore/Massmine-for-the-Masses/files/3587133/Related.files.zip)

**Comment by PatriciaTanzer** [comment]
Hi @AnushaVanama! Can you show us the contents of your settings file?

**Comment by PatriciaTanzer** [comment]
Oh wait I see the attachment, hang on

**Comment by PatriciaTanzer** [comment]
Ok @AnushaVanama it looks like for some reason the field that should exist in your settings file is no longer there. At the very bottom of the file, add a line that  looks like this:

**Comment by PatriciaTanzer** [comment]
FIELD_ENCRYPTION_KEY = 'BHf17uGpCP4ocVW4vgFSLR4m7pIhlWyicntsZ2W7Pv4='

**Comment by PatriciaTanzer** [comment]
I will also say that if you are using this tool for development with other users, it's usually best not to run the two steps with changing the key, so that all the developers are encrypting the database the same way. Basically what we're doing here is creating a local variable and then pasting it into your settings file so that only you can encrypt/decrypt your database

**Comment by AnushaVanama** [comment]
@PatriciaTanzer Thank you so much for the quick help. It worked for me and I am able to run the project successfully.

**Comment by PatriciaTanzer** [comment]
Awesome! I'm glad that helped:)
