### ISSUE TITLE
Unknown TimeZone Error

### ISSUE THREAD

**Issue by AnushaVanama** [JoshCMoore/Massmine-for-the-Masses#225]
![image](https://user-images.githubusercontent.com/49127881/68519888-e5e08000-0261-11ea-935d-3c792e6ef668.png)
 @JoshCMoore @PatriciaTanzer @LoganHornbuckle @Momac546 
Hi All,
I am unable to make query in massmine. I am facing an unknown timezone error. I have attached the error screenshots for the same. I would also like to let you know that I tried updating Time Zone value as "UTC" in settings.py file. Then I am facing twitter authentication error. If I remove UTC, I am facing server error. 
Could you please help me in resolving this issue?
![image](https://user-images.githubusercontent.com/49127881/68519947-48398080-0262-11ea-96c2-89e30f320d41.png)

**Comment by Momac546** [comment]
Hello! So the files throwing errors are mostly generated by django. I
believe the time_zone variable needs to remain blank (in
src/webapp/webappproject/settings.py). We added another variable in this
file, time = 'UTC'. You need to go into the django generated files in this
error
(/home/anusha/environ/lib/python3.6/site-packages/django/utils/timezone.py,
etc.) and change the variable here from 'time_zone' to 'time' so that the
time zone is recognized as being UTC. This should fix your problem. It's
not a great solution, but if you find a better one let us know! Good luck!

**Comment by AnushaVanama** [comment]
[settings.txt](https://github.com/JoshCMoore/Massmine-for-the-Masses/files/3827630/settings.txt)
[timezone.txt](https://github.com/JoshCMoore/Massmine-for-the-Masses/files/3827631/timezone.txt)

@Momac546 - TIME_ZONE = ' ' is blank in src/webapp/webappproject/settings.py.
But, I am unable to find time_zone in timezone.py.
Kindly find the attached files for both settings.py and timezone.py.
Could you please look into them once and let me know what changes should be made in timezone.py.
Thank you so much for your continuous support

**Comment by Momac546** [comment]
Hey, I unfortunately don't have this project on my computer anymore.
Time_zone is supposed to be blank, I believe we had issues with Massmine
when it wasn't empty. We had to use the 'time' variable to be set to utc
and change the variable name in various .py files in the environ folder
from time_zone to tine. The settings.py file matches the one we used since
it's on github! Can you search recursively in the django generated folders
for the time_zone variable?

**Comment by AnushaVanama** [comment]
[mozilla.pdf](https://github.com/JoshCMoore/Massmine-for-the-Masses/files/3827910/mozilla.pdf)
[EOF at _query_make_query_.txt](https://github.com/JoshCMoore/Massmine-for-the-Masses/files/3827902/EOF.at._query_make_query_.txt)

@Momac546 - I can see that  time_zone is already changed to time. Could you please check the below error screenshot and let me know if you have faced this kind of error earlier.

**Comment by Momac546** [comment]
It's already changed in your environ foldets/files?

**Comment by AnushaVanama** [comment]
@Momac546 - I went through your documentation again and found that I had already done the changes during the process of installation as mentioned in section 1.2.5.

There is also a time zone variable in the
environment file timezone.py that needs changed, to replace all instances of TIME_ZONE with
TIME. You can make these fixes with a text editor (except the key generation), but it is
probably faster to use the commands below.
• cd && sed -i “s/TIME_ZONE/TIME/g”
django/environ/lib/python3.6/site-packages/django/utils/timezone.py 

Could you please let me know whether I need to do any more changes other than this?

**Comment by Momac546** [comment]
I don't think we needed to do anything other than that to get it working on
our systems.

**Comment by AnushaVanama** [comment]
@Momac546 @JoshCMoore @PatriciaTanzer @LoganHornbuckle 
Hi All,
Currently, I am facing the below issues after the time change which happened on November 3rd.

[Make_Query_Failed.txt](https://github.com/JoshCMoore/Massmine-for-the-Masses/files/3849330/Make_Query_Failed.txt)

1. When Time_Zone is blank in settings.py
In this case, the query is working fine, the Admin page is not working.

2. When Time_Zone is set to UTC in settings.py
In this case, the query is not working and the Admin page is working. I have attached the error screenshot page which is displayed after clicking the submit query button.

In Particular, I can see that it is failing in the below lines and I tried checking what value is passed in the consumer key and it is the correct key which is the same as in the success scenario.
File "/home/anusha/django/webapp/query/views.py", line 51, in make_query
    if (validate_massmine(request) == 1):
  File "/home/anusha/django/webapp/query/views.py", line 36, in validate_massmine
    child.expect('Consumer key:')

Kindly help me in resolving this issue and please let me know if you have noticed similar issues in the past.

**Comment by AnushaVanama** [comment]
Hi All,

I am able to fix the issue by reinstalling everything from scratch. I left TIME_ZONE as blank.
Now, all the functionalities are working fine.
Thank you all for your support.

I am closing this issue now.

**Comment by Momac546** [comment]
That's really good to hear. Are you able to make queries and look at
analyses? Feel free to edit the installation instructions to reflect how
you fixed yours locally.

**Comment by AnushaVanama** [comment]
Yup, I tried doing many queries and all are working as expected. I went through the analysis tab and checked all 4 types of analysis for the query which I made. All the results are displaying correctly.

Coming to changes, I just reinstalled everything. I did not modify any of your existing code
